script:
  - echo 'Syntax check...'
  - echo 'Syntax ok''
  - ./scripts/run_tests small
  - ./scripts/deploy_code dev
  - ./scripts/run_tests medium
  - ./scripts/deploy_code qa
  - ./scripts/run_tests large
deploy:
  - provider: script
    script: ./scripts/deploy_code production
    on:
      branch: master

