before_install:
  - sudo npm cache clean -f
  - sudo npm install -g n
  - sudo n stable
script:
  - node --version
  - for file in `find -type f -name "*.js"`; do node -c $file; done
  - ./scripts/run_tests small
  - ./scripts/deploy_code dev
  - ./scripts/run_tests medium
  - ./scripts/deploy_code qa
  - ./scripts/run_tests large
deploy:
  - provider: script
    script: ./scripts/deploy_code production
    on:
      branch: master

